<div id="main">
    <h1>Kontakt</h1>
    formularz kontaktowy...
</div>

<!-- additional -->
<div id="additional">
    <div class="block">
        <img src="/img/tmp/ad.png" alt="" title="" />
    </div>

    <div class="block">
        <h3>1000 postów temu ...</h3>
        <span class="subtext">
            Poniedziałek, 16 lutego 2011 - 211 dni, 11 godzin i 23 minuty temu
        </span>
        <img src="/img/tmp/block.png" alt="" title="" />
    </div>
</div>