<div id="post">
    <div class="info">
        <h1><?php echo $this->post['title'] ?></h1>
        <h3><a href="<?php echo $this->url(array('name' => $this->post['author']), 'author') ?>"><?php echo $this->post['author'] ?></a></h3> - <span class="subtext"><?php echo $this->post['added'] ?>
            <p>
                <?php echo $this->post['source'] ?>
            </p>
        </span>
    </div>
    
    <img class="post" src="<?php echo $this->storageHost ?>/view/<?php echo Jk_File::getHashedDirStructure($this->post['post_id']); ?>-<?php echo $this->post['file'] ?>">
</div>