<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl" itemscope itemtype="http://schema.org/Blog">
<!--  xmlns:og="http://opengraphprotocol.org/schema/" -->
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headScript(); ?>

<link href='http://fonts.googleapis.com/css?family=Oxygen&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Dosis:600&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

<?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/site.css'); ?>
<?php echo $this->render('_partials/fb/og.phtml'); ?>
<?php echo $this->render('_partials/google/analytics.phtml'); ?>
<?php echo $this->render('_partials/google/plusOneHeader.phtml'); ?>
</head>
<body>
    <?php echo $this->render('_partials/fb/initJSSDK.phtml'); ?>
    <div id="page">
        <!-- header -->
        <div id="header">
            <a href="/"><img src="/img/poebao.png" alt="Poebao, content is king" title="Poebao, content is king"><h1 class="hidden">Poebao, content is king</h1></a>
            <div id="nav">
                <ul>
                    <li class="first"><a href="/oczekujace">oczekujące</a></li>
                    <li>
                        <!-- <a id="nav-show-upload-form" href="<?php echo $this->url(array(), 'postupload');?>">dodaj</a> -->
                    </li>
                    <?php if ($this->identity): ?>
                        <li><a href="<?php echo $this->url(array(), 'moderation') ?>">moderacja</a></li>
                        <li><a href="<?php echo $this->url(array(), 'userlogout') ?>">wyloguj (<?php echo $this->identity['username'] ?>)</a></li>
                    <?php endif ?>
                    
                </ul>
            </div>
        </div>
        
        <?php if ($this->messages): ?>
            <?php foreach ($this->messages as $key => $value): ?>
                <div class="message <?php echo $value['type']; ?>">
                    <?php if (!empty($value['title'])): ?>
                        <h2><?php echo $value['title'] ?></h2>
                    <?php endif ?>
                    <p><?php echo $value['content'] ?></p>
                </div>
            <?php endforeach ?>
        <?php endif ?>

        <!-- main content -->
        <div id="content">
            <div id="main">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>

        <!-- footer -->
        <div id="footer">
        poebao.pl (c) 2012 - <a href="/regulamin" target="_blank">Regulamin</a> | <a href="/kontakt">Kontakt</a>
        </div>
    </div>
</body>
</html>