<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl" itemscope itemtype="http://schema.org/Blog">
<!--  xmlns:og="http://opengraphprotocol.org/schema/" -->
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headScript(); ?>

<link href='http://fonts.googleapis.com/css?family=Oxygen&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Dosis:600&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

<?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/site.css'); ?>
<?php echo $this->render('_partials/fb/og.phtml'); ?>
<?php echo $this->render('_partials/google/analytics.phtml'); ?>
<?php echo $this->render('_partials/google/plusOneHeader.phtml'); ?>
</head>
<body>
    <?php echo $this->render('_partials/fb/initJSSDK.phtml'); ?>
    <!-- header -->
    <div id="header-container">
        <div id="header">
            <a href="/"><img src="/img/poebao.png" alt="Poebao, content is king" title="Poebao, content is king"><h1 class="hidden">Poebao, content is king</h1></a>
            <div id="nav">
                <ul>
                    <li class="first"><a class="fancy-hover"href="/oczekujace">oczekujące</a></li>
                    <li>
                        <a class="fancy-hover" id="nav-show-upload-form" href="<?php echo $this->url(array(), 'postupload');?>">dodaj</a>
                    </li>
                    <?php if ($this->identity): ?>
                        <li><a class="fancy-hover" href="<?php echo $this->url(array(), 'moderation') ?>">moderacja</a></li>
                        <li><a class="fancy-hover" href="<?php echo $this->url(array(), 'admin-logout') ?>">wyloguj (<?php echo $this->identity['username'] ?>)</a></li>
                    <?php endif ?>
                    
                </ul>
            </div>
        </div>
    </div>

    <div id="page">
        <?php if ($this->messages): ?>
            <?php foreach ($this->messages as $key => $value): ?>
                <div class="message <?php echo $value['type']; ?>">
                    <?php if (!empty($value['title'])): ?>
                        <h2><?php echo $value['title'] ?></h2>
                    <?php endif ?>
                    <p><?php echo $value['content'] ?></p>
                </div>
            <?php endforeach ?>
        <?php endif ?>

        <!-- main content -->
        <div id="content">
            <div id="main">
                <?php echo $this->layout()->content; ?>
            </div>


            <div id="additional">
                <div id="scroller-anchor"></div>
                <div id="scroller">
                    <div class="block">
                        <h3>1000 postów temu ...</h3>
                        <span class="subtext">Poniedziałek, 16 lutego 2011 - 211 dni, 11 godzin i 23 minuty temu</span>
                        <img src="/img/tmp/block.png" alt="" title="" />
                    </div>
    
                    <!-- footer -->
                    <div id="footer">
                    poebao.pl (c) 2012 - <a class="fancy-hover" href="/regulamin">Regulamin</a> | <a class="fancy-hover" href="mailto:kontakt@poebao.pl">Kontakt</a>
                    </div>
                </div>
            </div>
        </div>

        <?php if ($this->layerInfo): ?>
            <div id="layer" class="top-layer">
                <div class="body">
                    <h2>Przykro nam, ale podana strona nie istnieje [404]</h2>
                    <p>Strona do której prowadzi link w adresie, prawdopdobnie została skasowana, zmieniono jej nazwę lub została czasowo usunięta</p>
                    <input class="close" type="submit" value="Zamknij" />
                </div>
            </div>    
        <?php endif ?>
        

        <!-- footer -->
        <!-- <div id="footer">
        poebao.pl (c) 2012 - <a class="fancy-hover" href="/regulamin">Regulamin</a> | <a class="fancy-hover" href="mailto:kontakt@poebao.pl">Kontakt</a>
        </div> -->
        
        <!-- <div id="upload-form-layer">
            <div class="container">
                <span id="nav-hide-upload-form">X</span>
                <h2>Dodaj post</h2>
                <?php echo $this->postForm; ?>    
            </div>
        </div> -->

    </div>
</body>
</html>