<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/poebao.js') ?>

<!-- <link href='http://fonts.googleapis.com/css?family=Didact+Gothic&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'> -->

<?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/site.css'); ?>
</head>
<body>
    <div id="page">

        <!-- header -->
        <div id="header">
            <a href="<?php echo $this->url(array(), 'home'); ?>"><img src="/img/poebao.png" alt="Poebao, content is king" title="Poebao, content is king"><h1 class="hidden">Poebao, content is king</h1></a>
            <div id="nav">
                <ul>
                    <li class="first"><a href="<?php echo $this->url(array(), 'awaiting'); ?>">oczekujące</a></li>
                    <li>
                        <a id="show-upload" onclick="showUploadForm(); return false;" href="<?php echo $this->url(array(), 'post');?>">dodaj</a>
                    </li>
                    <?php if ($this->identity): ?>
                        <li><a href="<?php echo $this->url(array(), 'moderation') ?>">moderacja</a></li>
                        <li><a href="<?php echo $this->url(array(), 'logout') ?>">wyloguj (<?php echo $this->identity['username'] ?>)</a></li>
                    <?php endif ?>
                    
                </ul>
            </div>
        </div>
        
        <?php if ($this->messages): ?>
            <?php foreach ($this->messages as $key => $value): ?>
                <div class="message <?php echo $value['type']; ?>"><?php echo $value['content'] ?></div>
            <?php endforeach ?>
        <?php endif ?>

        <!-- main content -->
        <div id="content">
            <div id="main">
                <?php echo $this->layout()->content; ?>
            </div>
            <div id="additional">
                <div class="block">
                    <img src="/img/tmp/ad.png" alt="" title="" />
                </div>

                <div class="block">
                    <h3>1000 postów temu ...</h3>
                    <span class="subtext">Poniedziałek, 16 lutego 2011 - 211 dni, 11 godzin i 23 minuty temu</span>
                    <img src="/img/tmp/block.png" alt="" title="" />
                </div>
            </div>
        </div>

        <!-- footer -->
        <div id="footer">
        poebao.pl (c) 2012 - <a href="/regulamin">Regulamin</a> | <a href="/kontakt">Kontakt</a>
        </div>
        

        <div id="upload">
            <div class="container">
                <span id="closebutton">X</span>
                <h2>Dodaj post</h2>
                <?php echo $this->postForm; ?>    
            </div>
        </div>
        <?php if ($this->showUpload): ?>
            <script type="text/javascript">
            showUploadForm();
            </script>
        <?php endif ?>

    </div>
</body>
</html>