<!-- <h1><?php echo $this->escape($this->title); ?></h1> -->
<div id="posts">
    <ul class="post-list">
        <?php foreach ($this->paginator as $key => $value): ?>
            <a name="post-<?php echo $value->post_id ?>"></a>
            <li class="post-element <?php echo (!$key)?' first':'' ?>">
                <div class="img">
                    <a href="<?php echo $this->url(array('id' => $value->post_id, 'name' => $value->author), $this->postViewRoute) ?>">
                        <img class="post" src="<?php echo $value->image('thumb'); ?>">
                    </a>
                </div>
                    <div class="smallslimstick"></div>
                <?php
                if ($this->identity) {
                    echo $this->partial('moderation/_postModeration.phtml', array('post' => $value));
                }
                ?>
                <div class="info">
                    <h2><a class="fancy-hover" href="<?php echo $this->url(array('id' => $value->post_id, 'name' => $value->author), $this->postViewRoute) ?>"><?php echo $value->title ?></a></h2>
                    <span class="subtext">
                        <p>
                            <a class="fancy-hover" href="<?php echo $this->url(array('name' => $value->author), 'author') ?>"><?php echo $value->author ?></a> - <time class="timeago" datetime="<?php echo $value->added ?>"><?php echo $value->added ?></time>
                        </p>
                        <p><span class="source">
                            <?php if (filter_var($value->source, FILTER_VALIDATE_URL) !== false): ?>
                                <a class="fancy-hover" href="<?php echo $value->source ?>" target="_blank"><?php echo $value->source ?></a>
                            <?php else: ?>
                                <?php echo $value->source ?>    
                            <?php endif ?>
                            </source>
                        </p>
                    </span>
                    <div class="social-buttons">
                        <div class="social-button social-button-g-plus">
                            <?php echo $this->partial('_partials/google/plusOne.phtml', array('shareUrl' => $this->url(array('id' => $value->post_id, 'title' => $value->title), 'postview'))); ?>
                        </div>
                        <div class="social-button social-button-fb-like">
                            <?php echo $this->partial('_partials/fb/like.phtml', array('shareUrl' => $this->url(array('id' => $value->post_id, 'title' => $value->title), 'postview'))); ?>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
</div>

<?php echo $this->paginator; ?>