<!-- <h1><?php echo $this->escape($this->title); ?></h1> -->
<ul id="posts">
    <?php foreach ($this->paginator as $key => $value): ?>
        <li <?php echo ((!$key)?'class="first" ':''); ?>href="post-<?php echo $value->id ?>">
            <a href="<?php echo $this->url(array('id' => $value->post_id, 'title' => $value->title), 'postview') ?>"><img class="post" src="<?php echo $value->image('thumb'); ?>"></a>
            <?php
            if ($this->identity) {
                echo $this->partial('moderation/_postModeration.phtml', array('post' => $value));
            }
            ?>
            <div class="info">
                <h2><a href="<?php echo $this->url(array('id' => $value->post_id, 'title' => $value->title), 'postview') ?>"><?php echo $value->title ?></a></h2>
                <span class="subtext">
                    <p>
                        <a href="<?php echo $this->url(array('name' => $value->author), 'author') ?>"><?php echo $value->author ?></a> - <time class="timeago" datetime="<?php echo $value->added ?>"><?php echo $value->added ?></time>
                    </p>
                    <p><span class="source">
                        <?php if (filter_var($value->source, FILTER_VALIDATE_URL) !== false): ?>
                            <a href="<?php echo $value->source ?>" target="_blank"><?php echo $value->source ?></a>
                        <?php else: ?>
                            <?php echo $value->source ?>    
                        <?php endif ?>
                        </source>
                    </p>
                </span>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<?php echo $this->paginator; ?>