<div class="block">
    <h3><a href="<?php echo $this->url(array('page' => $this->block->postsAgo->posts[0]->getPageNum()), $this->blockPostViewRoute) ?>#post-<?php echo $this->block->postsAgo->posts[0]->post_id; ?>"><?php echo $this->block->postsAgo->offset ?> postów temu ...</a></h3>
    <span class="subtext">
        <time class="timeago" datetime="<?php echo $this->block->postsAgo->posts[0]->added ?>"><?php echo $this->block->postsAgo->posts[0]->added ?></time>
    </span>
    <ul id="posts-ago">
    <?php foreach ($this->block->postsAgo->posts as $key => $value): ?>
        <li id="posts-ago-<?php echo $key ?>">
            <div class="img">
                <a href="<?php echo $this->url(array('page' => $value->getPageNum()), $this->blockPostViewRoute) ?>#post-<?php echo $value->post_id; ?>">
                    <img class="post" src="<?php echo $value->image('thumb'); ?>">
                </a>
            </div>
        </li>
    <?php endforeach ?>
    </ul>
</div>