<!-- <a class="left" href="<?php echo $this->url(array(), 'awaiting') ?>">« Wróć do oczekujących</a> -->
<div class="right">
    <?php if (!is_null($this->post->getPrevious())): ?>
        <a class="button button-wider button-taller" href="<?php echo $this->url(array('id' => $this->post->getPrevious()->getPostId(), 'title' => $this->post->getPrevious()->getTitle()), 'postview') ?>">❮❮</a>    
    <?php endif ?>
    <?php if (!is_null($this->post->getNext())): ?>
        <a class="button button-wider button-taller" href="<?php echo $this->url(array('id' => $this->post->getNext()->getPostId(), 'title' => $this->post->getNext()->getTitle()), 'postview') ?>">❯❯</a>
    <?php endif ?>
</div>

<div id="post" class="clear">
    <div class="info">
        <h1><?php echo $this->post->getTitle(); ?></h1>
        <h3 class="subtext"><a href="<?php echo $this->url(array('name' => $this->post->getAuthor()), 'author') ?>"><?php echo $this->post->getAuthor() ?></a></h3> - <span class="subtext"><time class="timeago" datetime="<?php echo $this->post->getAdded() ?>"><?php echo $this->post->getAdded() ?></time> - 
            <span class="source">
                <?php if (filter_var($this->post->getSource(), FILTER_VALIDATE_URL) !== false): ?>
                    <a href="<?php echo $this->post->getSource() ?>" target="_blank"><?php echo $this->post->getSource() ?></a>
                <?php else: ?>
                    <?php echo $this->post->getSource() ?>    
                <?php endif ?>
            </span>
        </span>
    </div>
    
    <img class="post" src="<?php echo $this->storageHost ?>/view/<?php echo Jk_File::getHashedDirStructure($this->post->getPostId()); ?>-<?php echo $this->post->getFile() ?>">
</div>