<!-- <a class="left" href="<?php echo $this->url(array(), 'awaiting') ?>">« Wróć do oczekujących</a> -->
<!-- <div class="right"><a href="">❮❮</a> | <a href="">❯❯</a></div> -->

<div id="post" class="clear">
    <div class="info">
        <h1><?php echo $this->post['title'] ?></h1>
        <h3 class="subtext"><a href="<?php echo $this->url(array('name' => $this->post['author']), 'author') ?>"><?php echo $this->post['author'] ?></a></h3> - <span class="subtext"><?php echo $this->post['added'] ?> - 
            <span class="source">
                <?php if (filter_var($this->post['source'], FILTER_VALIDATE_URL) !== false): ?>
                    <a href="<?php echo $this->post['source'] ?>" target="_blank"><?php echo $this->post['source'] ?></a>
                <?php else: ?>
                    <?php echo $this->post['source'] ?>    
                <?php endif ?>
            </span>
        </span>
    </div>
    
    <img class="post" src="<?php echo $this->storageHost ?>/view/<?php echo Jk_File::getHashedDirStructure($this->post['post_id']); ?>-<?php echo $this->post['file'] ?>">
</div>