<a class="left fancy-hover" href="<?php echo $this->url(array('name' => $this->author, 'page' => $this->post->getPageNum()), $this->listRoute) ?>#post-<?php echo $this->post->post_id; ?>">« Wróć do listy</a>
<div class="right">
    <?php if (!is_null($this->post->getPrevious())): ?>
        <a class="button button-wider button-taller" id="nav-post-view-prev" href="<?php echo $this->url(array('id' => $this->post->getPrevious()->post_id, 'title' => $this->post->getPrevious()->title), $this->postViewRoute) ?>"><<</a>    
    <?php endif ?>
    <?php if (!is_null($this->post->getNext())): ?>
        <a class="button button-wider button-taller" id="nav-post-view-next" href="<?php echo $this->url(array('id' => $this->post->getNext()->post_id, 'title' => $this->post->getNext()->title), $this->postViewRoute) ?>">>></a>
    <?php endif ?>
</div>

<div id="post" class="clear">
    <div class="info">
        <h1><?php echo $this->post->title; ?></h1>
        <h3 class="subtext"><a class="fancy-hover" href="<?php echo $this->url(array('name' => $this->post->author), 'author') ?>"><?php echo $this->post->author ?></a></h3> - <span class="subtext"><time class="timeago" datetime="<?php echo $this->post->added ?>"><?php echo $this->post->added ?></time>
        <?php if ($this->post->source): ?>
            -
            <span class="source">
                <?php if (filter_var($this->post->source, FILTER_VALIDATE_URL) !== false): ?>
                    <a class="fancy-hover" href="<?php echo $this->post->source ?>" target="_blank"><?php echo $this->post->source ?></a>
                <?php else: ?>
                    <?php echo $this->post->source ?>    
                <?php endif ?>
            </span>
        <?php endif ?>
        </span>
    </div>

    <!-- <div class="center"> -->
        <div class="center social-buttons">
            <div class="social-button social-button-g-plus">
                <?php echo $this->partial('_partials/google/plusOne.phtml', array('shareUrl' => $this->url(array('id' => $this->post->post_id, 'title' => $this->post->title, 'name' => $this->post->author), 'author-postview'))); ?>
            </div>
            <div class="social-button social-button-fb-like">
                <?php echo $this->partial('_partials/fb/like.phtml', array('shareUrl' => $this->url(array('id' => $this->post->post_id, 'title' => $this->post->title, 'name' => $this->post->author), 'author-postview'))); ?>
            </div>
        </div>
    <!-- </div> -->
        
    <div class="img">
        <?php if (!is_null($this->post->getNext())): ?>
            <a href="<?php echo $this->url(array('id' => $this->post->getNext()->post_id, 'title' => $this->post->getNext()->title), $this->postViewRoute) ?>">
        <?php endif ?>
        <img class="post" src="<?php echo $this->post->image('view'); ?>">
        <?php if (!is_null($this->post->getNext())): ?>
            </a>
        <?php endif ?>


        <div class="twoja-stara"></div>
    </div>
</div>

<div id="fb-comments">
    <?php echo $this->render('_partials/fb/comments.phtml'); ?>
</div>